version: '3.8'
services:

  db:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_PORT: ${MYSQLDB_DATABASE_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    volumes:
      - data:/var/lib/mysql

  backend:
    container_name: backend
    image: kostavigulear/rbac-backend:0.0.1
    restart: always
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${MYSQLDB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_PASSWORD}
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: kostavigulear/rbac-frontend:latest
    restart: always
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: